/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "tertiary": "#904900",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#c3c0ff",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#464554",
        "on-primary-fixed": "#07006c",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed": "#0f0069",
        "primary-fixed": "#e1e0ff",
        "surface-container": "#e5eeff",
        "primary": "#4648d4",
        "background": "#f8f9ff",
        "outline": "#767586",
        "secondary": "#4b41e1",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#c0c1ff",
        "primary-container": "#6063ee",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#3323cc",
        "secondary-fixed": "#e2dfff",
        "surface-tint": "#494bd6",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#645efb",
        "surface-dim": "#cbdbf5",
        "surface": "#f8f9ff",
        "tertiary-fixed": "#ffdcc5",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c4d7",
        "tertiary-container": "#b55d00",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary-fixed-variant": "#703700"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "card": "10px",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "md": "16px",
        "base": "4px",
        "3xl": "64px",
        "container-max": "1440px",
        "xs": "4px",
        "2xl": "48px",
        "sm": "8px",
        "lg": "24px",
        "xl": "32px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
